model_params:
  model: cell_senet
  model_name: se_resnext50_32x4d
  n_channels: 3
  num_classes: 1108

args:
  expdir: "src"
  logdir: &logdir "./logs/cell"
  baselogdir: "./logs/cell"

distributed_params:
  opt_level: O1

stages:

  state_params:
    main_metric: &reduce_metric accuracy01
    minimize_metric: False

  criterion_params:
#    criterion: CrossEntropyLoss
    criterion: LabelSmoothingCrossEntropy

  optimizer_params:
    optimizer: AdamW
    lr: 0.0001
#    weight_decay: 0.0001

  scheduler_params:
    scheduler: OneCycleLR
    num_steps: &num_epochs 30
    lr_range: [0.0005, 0.00001]
    warmup_steps: 5
    momentum_range: [0.85, 0.95]

  data_params:
    batch_size: 64
    num_workers: 4
    drop_last: False

    image_size: &image_size 512
    train_csv: "./csv/train_0.csv"
    valid_csv: "./csv/valid_0.csv"
    root: "/raid/data/kaggle/recursion-cellular-image-classification/"
    site: 1
    channels: [1, 2, 3]

  stage1:

    state_params:
      num_epochs: *num_epochs

    callbacks_params: &callback_params
      loss:
#        callback: CriterionCallback
        callback: LabelSmoothCriterionCallback
      optimizer:
        callback: OptimizerCallback
        accumulation_steps: 2
      accuracy:
        callback: AccuracyCallback
        accuracy_args: [1]
      scheduler:
        callback: SchedulerCallback
        reduce_metric: *reduce_metric
      saver:
        callback: CheckpointCallback

#  stage2:
#
#    state_params:
#      num_epochs: 9
#
#    optimizer_params:
#      optimizer: Adam
#      lr: 0.0001
#      weight_decay: 0.0001
#
#    callbacks_params: *callback_params